version: '3'

services:
  web:
    container_name: debio-conversion
    image: debionetwork/debio-conversion
    build:
      context: ../../
      dockerfile: .maintain/docker/Dockerfile
    env_file:
      - ../../.env
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - 3002:3000
    networks:
      debio:
        ipv4_address: 172.27.1.12
        aliases:
          - debio-conversion

networks:
  debio:
    external: true
